### ISSUE TITLE
npm下载下来后，执行link，再把代码加进去之后报MobclickAgent，RNUMConfigure找不到符号

### ISSUE THREAD

**Issue by liu-miao-miao** [fenglu09/react-native-umeng#2]
请问应该怎么在MainActivity.java，MainApplication.java把MobclickAgent，RNUMConfigure引入进来呢

**Comment by fenglu09** [comment]
在`MainApplication.java`中加入`import com.jason.rctumeng.RNUMConfigure;`
在`MainActivity.java`中加入`import com.umeng.analytics.MobclickAgent;`
用Android Studio打开后，IDE应该会自动提示引入；
